name: Code Run Check

on:
  issue_comment:
    types: [created]
    
jobs:
  run_comment_check:
    runs-on: [ubuntu-latest]
    steps:
    - name: Pull Request Comment Trigger
      # You may pin to the exact commit or the version.
      # uses: Khan/pull-request-comment-trigger@af6260d48c05e1f2f1641f9d14794bd04687c023
      uses: Khan/pull-request-comment-trigger@v1.1.0
      with:
        # The emoji "reaction" to put on the comment to indicate that the trigger was detected. For example, "rocket"
        trigger: "gregory"
        # The string to look for in pull-request descriptions and comments. For example "#build/android"
