name: Testing file directory

on:
  workflow_dispatch:

jobs:
  Testing_Directory:
    runs-on: [ubuntu-latest]

    steps:

      - name: Print the GitHub context to console
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v3.5.1
        
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id "$aws-access-key-id" 
          aws configure set aws_secret_access_key "$aws-secret-access-key"
          aws configure set region "us-east-1"
          aws configure set output "text"
        env:
          aws-access-key-id: test
          aws-secret-access-key: test
          aws-region: us-east-1

      - name: Check AWS credentials file in file directory
        run: |
          cd ~
          ls -a
          cd .aws
          ls -a
          cat credentials
