name: Testing file directory

on:
  workflow_dispatch:

jobs:
  Testing_Directory:
    runs-on: [ubuntu-latest]

    steps:

      - name: Print the GitHub contexts to console
        run: |
          echo ${{ github.workspace }}

      - name: Checkout repository
        uses: actions/checkout@v3.5.1
        
      - name: Configure AWS credentials
        run: |
          echo "$AWS_ACCESS_KEY_ID"
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
          aws configure set output "text"
        env:
          AWS_ACCESS_KEY_ID: testaction
          AWS_SECRET_ACCESS_KEY: testaction
          AWS_REGION: us-east-1
          
      - name: Install EB CLI
        uses: sparkplug-app/install-eb-cli-action@v1.1.1
        
      - name: Check EB version
        run: eb --version
          
          # "/home/runner" is root(~) directory where AWS Creds are set
          # "/home/runner/work/valorant-agent-assistant/valorant-agent-assistant/" is checkout directory
      - name: Copy AWS creds to src code directory
        run: cp -R /home/runner/.aws/ /home/runner/work/valorant-agent-assistant/valorant-agent-assistant/.aws/

      - name: Check AWS credentials file in working actions directory
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -a
          cd .aws
          cat credentials
