name: Testing file directory

on:
  workflow_dispatch:

jobs:
  Testing_Directory:
    runs-on: [ubuntu-latest]

    steps:

      - name: Print the GitHub contexts to console
        run: |
          echo ${{ github.workspace }}

      - name: Checkout repository
        uses: actions/checkout@v3.5.1
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "testing with actions"
          aws-secret-access-key: "testing with actions v2222"
          aws-region: "us-east-1"
          
          # "/home/runner" is root(~) directory where AWS Creds are set
          # "/home/runner/work/valorant-agent-assistant/valorant-agent-assistant/" is checkout directory
      - name: Copy AWS creds to src code directory
        run: cp -R /home/runner/.aws/ /home/runner/work/valorant-agent-assistant/valorant-agent-assistant/.aws/

      - name: Check AWS credentials file in working actions directory
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -a
          cd .aws
          cat credentials
